# Importing of Libraries

In [1]:
import numpy as np
import pandas as pd


import matplotlib.pyplot as plt
import matplotlib.style as style
import seaborn as sns


# from sklearn.base import BaseEstimator, TransformerMixin
# 
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import KNNImputer
from category_encoders import TargetEncoder

from sklearn.feature_selection import SelectFromModel


from sklearn.model_selection import cross_val_score, KFold, train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.metrics import mean_absolute_error

from catboost import CatBoostRegressor
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.linear_model import BayesianRidge


import optuna


import tqdm
import joblib
import pickle
# serializd your object and svaes its binary form 

import shap


pd.set_option('display.max_columns', 70)
plt.rcParams['axes.spines.top']=False
plt.rcParams['axes.spines.right']=False

style.use('ggplot')
sns.set_palette('Set2')
# blue, orange, green

import warnings
warnings.filterwarnings('ignore')

# The Data

In [18]:
train = pd.read_csv('EUI.csv')
test = pd.read_csv('x_test.csv')

In [19]:
y_test=pd.read_csv('y_test.csv')

In [20]:
for i in train.columns:
    print(train[i].value_counts())

0        1
50493    1
50509    1
50508    1
50507    1
        ..
25252    1
25251    1
25250    1
25249    1
75756    1
Name: id, Length: 75757, dtype: int64
6    22449
5    18308
4    12946
3    10879
2     9058
1     2117
Name: Year_Factor, dtype: int64
State_6     50840
State_11     6412
State_1      5618
State_2      4871
State_4      4300
State_8      3701
State_10       15
Name: State_Factor, dtype: int64
Residential    43558
Commercial     32199
Name: building_class, dtype: int64
Multifamily_Uncategorized                    39455
Office_Uncategorized                         12512
Education_Other_classroom                     3860
Lodging_Hotel                                 2098
2to4_Unit_Building                            1893
Commercial_Other                              1744
5plus_Unit_Building                           1273
Warehouse_Nonrefrigerated                     1255
Retail_Uncategorized                          1130
Education_College_or_university               1056
Nursing_Home                                   772
Education_Uncategorized                        709
Mixed_Use_Commercial_and_Residential           672
Lodging_Dormitory_or_fraternity_sorority       669
Warehouse_Distribution_or_Shipping_center      604
Warehouse_Selfstorage                          577
Grocery_store_or_food_market                   448
Office_Medical_non_diagnostic                  447
Health_Care_Inpatient                          409
Religious_worship                              399
Industrial                                     384
Warehouse_Uncategorized                        330
Mixed_Use_Predominantly_Commercial             256
Parking_Garage                                 251
Office_Bank_or_other_financial                 173
Public_Assembly_Library                        160
Public_Safety_Fire_or_police_station           157
Public_Assembly_Other                          142
Service_Vehicle_service_repair_shop            138
Retail_Enclosed_mall                           120
Retail_Strip_shopping_mall                     113
Warehouse_Refrigerated                         113
Public_Assembly_Entertainment_culture          110
Education_Preschool_or_daycare                 108
Laboratory                                     107
Commercial_Unknown                              95
Public_Assembly_Social_meeting                  88
Lodging_Other                                   75
Retail_Vehicle_dealership_showroom              74
Public_Assembly_Recreation                      72
Food_Sales                                      70
Public_Assembly_Drama_theater                   70
Service_Uncategorized                           68
Food_Service_Restaurant_or_cafeteria            64
Health_Care_Outpatient_Clinic                   56
Health_Care_Uncategorized                       51
Public_Safety_Uncategorized                     43
Public_Assembly_Movie_Theater                   39
Public_Safety_Courthouse                        38
Public_Safety_Penitentiary                      37
Health_Care_Outpatient_Uncategorized            36
Data_Center                                     27
Public_Assembly_Uncategorized                   25
Office_Mixed_use                                18
Food_Service_Uncategorized                      18
Food_Service_Other                              17
Mixed_Use_Predominantly_Residential              9
Public_Assembly_Stadium                          9
Service_Drycleaning_or_Laundry                   9
Lodging_Uncategorized                            5
Name: facility_type, dtype: int64
60000.0     264
70000.0     213
80000.0     176
75000.0     173
72000.0     173
           ...
450500.0      1
354100.0      1
123290.0      1
133280.0      1
40489.0       1
Name: floor_area, Length: 20433, dtype: int64
1927.0    2064
1929.0    1999
1928.0    1979
1930.0    1811
1925.0    1710
          ...
1878.0       1
1829.0       1
1844.0       1
1871.0       1
1815.0       1
Name: year_built, Length: 180, dtype: int64
100.0    1946
1.0       985
79.0      782
84.0      781
89.0      781
         ...
21.0      252
16.0      248
11.0      247
10.0      237
0.0         1
Name: energy_star_rating, Length: 101, dtype: int64
42.7     18822
3.4      12004
15.2      6399
18.3      4520
25.6      4072
         ...
813.5        1
80.8         1
128.0        1
381.9        1
93.9         1
Name: ELEVATION, Length: 193, dtype: int64
 11    22729
 8     12555
 4     10090
 13     8366
 28     6401
 3      2909
-2      2123
 6      1770
-8      1059
 29     1047
 37     1040
 41      896
 22      724
 27      636
 15      527
 36      486
 26      309
 10      305
-6       289
-9       285
-16      208
-4       202
-1       116
-10      113
 35       89
 25       51
 2        48
 39       47
 42       44
 24       35
 23       32
 18       25
 31       22
 49       19
 32       19
-18       18
 14       16
 30       13
 46       11
 21       10
 19       10
 43        9
 45        9
 38        9
-19        7
 33        7
 12        6
 16        3
 34        2
 20        2
-17        1
 17        1
-7         1
 5         1
 0         1
 47        1
 7         1
 1         1
 40        1
Name: january_min_temp, dtype: int64
34.451613    13015
29.854839    10144
28.596774     9267
37.322581     8362
35.080645     8296
             ...
53.032258        1
36.838710        1
50.693548        1
33.064516        1
52.467742        1
Name: january_avg_temp, Length: 165, dtype: int64
59    14385
56    13344
62    12470
58     9281
61     8608
63     3190
49     2402
50     2121
53     1746
69     1115
77     1079
46     1059
73      914
67      851
65      723
68      397
64      291
47      290
48      224
45      206
44      186
74      148
43      138
42       99
66       53
76       50
51       50
82       44
90       44
70       35
86       33
54       27
87       23
80       22
71       20
57       16
84       11
83       11
85       10
89        9
60        6
78        6
72        6
88        4
79        3
75        3
55        2
81        1
91        1
Name: january_max_temp, dtype: int64
 2     13940
-1     13015
 9      9267
 17     8811
 20     8368
 32     3213
 34     3204
 42     1973
 15     1746
 10     1403
 13     1375
 4      1158
 36     1096
-13     1062
-5       844
 12      823
 25      714
 14      698
 33      621
 35      382
 30      334
 1       289
 3       202
-10      201
-8       191
 37      143
-9       112
-7        99
-2        68
 39       67
 29       60
 27       57
 31       35
 46       28
-12       25
 21       20
 28       18
 16       18
 44       17
 48       11
 38       10
 26        8
 19        7
 5         5
 22        5
 18        3
 11        2
 6         2
 24        2
 40        2
-4         1
 23        1
-11        1
Name: february_min_temp, dtype: int64
37.706897    13015
23.946429    10144
31.625000     9267
40.879310     8362
33.910714     8296
             ...
51.767857        1
40.931034        1
51.017241        1
47.620690        1
54.267857        1
Name: february_avg_temp, Length: 168, dtype: int64
61    13310
62    12698
43    10144
56    10090
55     8413
64     4769
67     3147
75     2143
65     2130
44     2109
71     1604
68     1383
63      904
78      627
58      539
73      469
69      278
49      192
74      143
42      116
41       95
70       60
46       55
84       48
80       45
86       43
72       40
76       25
81       25
48       21
79       19
60       16
82       15
52       15
77        7
66        7
88        6
85        2
83        1
89        1
59        1
40        1
38        1
Name: february_max_temp, dtype: int64
 26    14946
 12    12265
 13     9267
 25     8377
 27     8309
 35     3254
 29     3213
 47     1931
 20     1753
 9      1559
 40     1434
 7      1370
 0      1060
 24      854
-1       844
 23      823
 32      732
 10      694
 34      631
 37      315
 22      305
 8       289
-2       223
 14      209
-9       193
 45      141
 6       116
-3        99
-6        95
-4        48
 46       47
 51       43
 43       35
 30       31
 39       30
 36       27
 44       27
 33       26
 42       20
 4        20
 50       19
-5        19
 48       16
 52       11
 41        9
 28        7
 31        5
 18        4
 15        4
 38        3
 16        2
 1         1
 5         1
 49        1
Name: march_min_temp, dtype: int64
48.870968    13015
38.096774    10144
37.661290     9267
50.935484     8362
40.145161     8296
             ...
48.903226        1
42.706897        1
38.306452        1
33.758065        1
69.758065        1
Name: march_avg_temp, Length: 166, dtype: int64
79    14730
62    10681
66     9289
78     8387
59     8296
71     6668
74     2292
73     2134
77     2060
76     1958
70     1592
82     1422
72     1246
85     1091
65      849
60      823
69      753
80      711
68      308
75      106
81       67
87       51
83       46
93       43
92       34
56       25
57       18
67       17
84       14
86       10
91       10
94        6
63        4
90        3
88        3
61        2
95        2
58        2
53        1
89        1
64        1
54        1
Name: march_max_temp, dtype: int64
26    13873
32    11707
31    10655
33     9030
38     8386
37     3798
40     3509
23     2123
47     1975
35     1760
28     1505
41     1410
24     1379
27     1252
18      853
25      848
34      752
21      302
44      133
29      111
43       72
36       55
42       43
30       38
51       33
39       30
52       27
48       23
45       22
46       20
22       18
49        9
17        2
16        2
15        1
19        1
Name: april_min_temp, dtype: int64
53.333333    13015
54.250000    10144
52.333333     9267
54.766667     8362
52.983333     8296
             ...
64.083333        1
54.800000        1
44.616667        1
49.666667        1
61.850000        1
Name: april_avg_temp, Length: 164, dtype: int64
82     22038
88     10497
80     10415
77      9408
78      4907
89      4037
81      2416
84      2075
83      1949
90      1809
91      1774
85      1414
86      1053
79       907
87       704
93        82
92        78
96        51
94        37
95        28
75        19
72        13
98        11
76        11
69         5
99         4
104        3
70         3
74         3
97         2
66         2
62         1
73         1
Name: april_max_temp, dtype: int64
49    17658
43    13045
48    10198
42     8346
45     5142
41     4591
47     2307
38     2291
46     2157
51     2082
35     2067
37     1676
44     1438
39      889
33      832
36      594
34      204
58       49
56       44
40       36
54       33
57       20
53       19
32       10
52        6
31        5
30        4
27        4
28        3
23        2
55        1
25        1
26        1
29        1
50        1
Name: may_min_temp, dtype: int64
62.790323    21311
68.516129    10144
64.000000     9267
65.096774     8362
59.193548     3197
             ...
52.661290        1
70.274194        1
64.903226        1
63.419355        1
82.112903        1
Name: may_avg_temp, Length: 165, dtype: int64
92     15468
88     13922
90     12959
86     11473
89     11196
81      3178
91      2907
94      2164
87      1204
84       660
85       126
104       81
96        56
97        55
98        46
95        42
100       33
93        30
102       29
79        22
82        16
103       13
77        13
76        10
72         9
99         8
80         7
83         6
109        6
78         4
101        3
73         2
105        2
112        2
64         1
108        1
74         1
65         1
71         1
Name: may_max_temp, dtype: int64
52    14575
51    10903
50    10635
55    10319
53     8998
47     4042
48     3822
56     3348
42     2152
45     1703
54     1397
41     1271
49      816
44      719
58      573
43      198
46      134
57       48
63       33
59       16
62       11
66        6
38        6
61        5
37        5
35        4
34        3
31        3
40        2
33        2
60        2
36        2
64        1
39        1
68        1
30        1
Name: june_min_temp, dtype: int64
72.250000    13015
71.183333    10144
72.450000     9267
70.983333     8377
72.650000     8296
             ...
83.050000        1
72.133333        1
75.900000        1
69.666667        1
89.550000        1
Name: june_avg_temp, Length: 162, dtype: int64
90     15503
88     13227
92      9798
89      9595
94      8914
95      6092
91      4771
97      2137
87      1939
106     1079
96       718
99       713
103      607
104      274
107       75
109       50
108       43
79        32
76        29
100       24
86        24
110       18
78        17
80        16
98        14
101        7
111        6
112        6
69         4
105        4
102        4
114        2
67         2
72         2
82         2
85         2
84         1
83         1
74         1
73         1
113        1
119        1
81         1
Name: june_max_temp, dtype: int64
63    25482
64    18493
61     9945
54     6419
55     5053
53     2690
57     1710
60     1578
51     1399
52      754
62      747
48      744
58      353
50      210
56       57
59       27
66       17
65       17
67       13
47       13
49       10
45        7
73        6
46        3
40        2
42        2
37        2
71        1
43        1
74        1
41        1
Name: july_min_temp, dtype: int64
78.677419    13015
78.790323    10144
76.145161     9267
78.758065     8362
79.838710     8296
             ...
66.983871        1
75.209677        1
76.758065        1
77.983871        1
94.435484        1
Name: july_avg_temp, Length: 161, dtype: int64
96     30137
91     11326
100     9783
98      8877
87      3246
95      2802
104     1763
97      1406
94      1157
90      1089
103     1085
81      1076
99       612
84       377
93       297
102      289
92       144
108       37
107       37
111       33
105       31
109       30
106       22
85        21
79        17
80        16
110        8
117        6
112        6
67         5
86         3
83         3
116        3
89         3
101        2
66         2
65         2
113        1
77         1
115        1
88         1
Name: july_max_temp, dtype: int64
61    32089
59    12310
63    10182
52     4780
51     4228
54     3578
55     1952
58     1183
50     1142
53     1112
57      949
41      846
45      709
56      258
48      230
62       88
49       34
65       18
67       15
46       13
60       10
44        8
68        6
66        4
42        4
37        3
77        2
40        1
72        1
31        1
64        1
Name: august_min_temp, dtype: int64
79.177419    13015
78.967742    10144
74.516129     9267
76.693548     8362
74.596774     8296
             ...
73.838710        1
77.129032        1
72.338710        1
65.935484        1
78.870968        1
Name: august_avg_temp, Length: 167, dtype: int64
90     18458
96     13053
91     12434
95     11320
89      5515
94      4379
98      2128
100     2022
92      1419
104     1093
76      1036
80       895
93       594
85       389
97       329
88       228
83       128
105       47
86        45
101       40
107       31
87        27
77        26
110       22
106       21
108       17
109       14
99        11
112        6
113        6
111        4
71         4
103        4
74         2
82         2
116        2
72         1
114        1
102        1
68         1
66         1
84         1
Name: august_max_temp, dtype: int64
54    13207
52    12118
56    11039
53     9418
47     8621
44     7431
51     4236
46     2811
48     2153
40     1694
49      919
45      737
42      719
41      358
61       43
58       39
59       38
50       36
38       22
60       20
39       16
37       15
43       12
65       12
64       11
62        7
36        5
55        4
32        4
35        4
26        2
31        2
29        1
28        1
63        1
27        1
Name: september_min_temp, dtype: int64
71.800000    13019
74.450000    10144
69.733333     9267
68.800000     8488
67.866667     8296
             ...
68.416667        1
66.916667        1
58.550000        1
64.700000        1
90.116667        1
Name: september_avg_temp, Length: 165, dtype: int64
91     21973
96     11989
97     10761
92      9600
93      4747
94      3654
79      3198
80      3182
86      1891
95      1426
105     1059
83       895
90       399
98       321
88       219
102       81
103       71
104       59
100       32
89        32
101       24
73        22
87        20
82        19
81        15
85        11
108       10
99        10
77         9
106        8
109        8
107        3
75         2
74         2
111        1
72         1
84         1
64         1
70         1
Name: september_max_temp, dtype: int64
38    22773
35    12457
42     9318
40     9013
39     3228
46     3207
34     2144
33     2045
32     1767
29     1098
49     1085
51     1059
28     1009
43      944
30      943
55      924
24      901
23      845
47      376
31      240
48      128
37       43
57       43
45       37
44       34
41       31
59       19
61       11
54       11
53       10
50        4
25        2
18        2
52        1
19        1
27        1
22        1
58        1
21        1
Name: october_min_temp, dtype: int64
58.048387    18506
58.758065    13015
59.629032     9267
60.193548     8296
55.403226     3197
             ...
67.193548        1
58.580645        1
45.693548        1
57.887097        1
80.741935        1
Name: october_avg_temp, Length: 168, dtype: int64
78     20793
85     14588
86     10559
77      9492
68      3197
74      3186
84      3066
83      2986
80      2353
81      1374
96      1063
95       938
100      610
88       574
82       307
93       157
79       125
103       58
89        45
92        34
94        32
75        28
97        27
98        25
87        24
90        24
59        22
101       19
99        14
91        12
76         9
108        5
102        4
105        2
73         2
60         2
72         1
Name: october_max_temp, dtype: int64
34    13103
32    10163
22     9966
31     9093
23     8299
27     3510
20     3489
40     3232
29     2617
36     2029
12     1905
19     1662
26     1420
44     1044
46      927
17      821
35      622
43      363
21      251
8       195
7       191
9       187
42      145
16      118
37       63
47       61
6        50
51       39
33       35
38       32
39       22
28       21
41       20
52       20
50       11
30        9
4         7
24        4
18        3
45        2
14        2
25        2
15        1
10        1
Name: november_min_temp, dtype: int64
49.766667    13015
52.783333    10144
45.300000     9267
43.866667     8362
45.250000     8296
             ...
44.566667        1
39.103448        1
40.733333        1
43.416667        1
66.050000        1
Name: november_avg_temp, Length: 160, dtype: int64
72    15470
74    10152
70    10043
69     9276
66     8373
71     5586
76     4893
59     3178
75     2823
81     1581
80     1447
73     1176
79      721
77      448
62      236
93       44
91       40
94       36
84       30
83       26
85       22
78       22
89       21
82       20
64       17
90       15
53       13
87       12
92        9
61        8
86        5
68        3
95        3
60        2
65        2
67        2
88        1
96        1
Name: november_max_temp, dtype: int64
 17    13118
 24    12787
 34    10153
 28    10056
 19     8821
 29     3206
 26     2286
-9      2121
 12     1980
 22     1836
 36     1432
 14     1403
 23     1396
 15     1177
 41      903
 18      850
 16      836
-10      491
 4       207
 13      186
 35      127
 44       58
 27       53
 33       45
 38       43
 30       27
 31       26
 21       22
 2        21
 20       21
 43       20
 25       12
 32        9
 9         8
 1         7
 10        3
-16        2
 39        2
 5         2
 3         1
-4         1
 37        1
 6         1
Name: december_min_temp, dtype: int64
38.338710    13015
50.774194    10144
40.516129     9267
41.467742     8362
38.548387     8296
             ...

In [21]:
for i in test.columns:
    print(test[i].value_counts())

7    9705
Name: Year_Factor, dtype: int64
State_11    3268
State_4     2568
State_2     1515
State_8     1323
State_1     1027
State_10       4
Name: State_Factor, dtype: int64
Commercial     5607
Residential    4098
Name: building_class, dtype: int64
Multifamily_Uncategorized                    2199
Office_Uncategorized                         1919
2to4_Unit_Building                            966
Education_Other_classroom                     890
5plus_Unit_Building                           685
Lodging_Hotel                                 367
Commercial_Other                              325
Retail_Uncategorized                          225
Education_College_or_university               202
Mixed_Use_Commercial_and_Residential          193
Warehouse_Uncategorized                       157
Nursing_Home                                  151
Grocery_store_or_food_market                  135
Religious_worship                             125
Warehouse_Nonrefrigerated                     110
Office_Medical_non_diagnostic                 100
Lodging_Dormitory_or_fraternity_sorority       99
Warehouse_Distribution_or_Shipping_center      94
Warehouse_Selfstorage                          80
Health_Care_Inpatient                          76
Mixed_Use_Predominantly_Commercial             50
Industrial                                     47
Laboratory                                     44
Parking_Garage                                 37
Retail_Strip_shopping_mall                     37
Retail_Enclosed_mall                           33
Public_Assembly_Recreation                     26
Office_Bank_or_other_financial                 23
Commercial_Unknown                             23
Warehouse_Refrigerated                         21
Public_Assembly_Entertainment_culture          20
Food_Sales                                     19
Public_Assembly_Library                        17
Food_Service_Restaurant_or_cafeteria           17
Public_Safety_Uncategorized                    16
Service_Uncategorized                          15
Public_Assembly_Drama_theater                  14
Public_Assembly_Social_meeting                 14
Public_Assembly_Movie_Theater                  13
Retail_Vehicle_dealership_showroom             12
Education_Uncategorized                        12
Service_Vehicle_service_repair_shop             9
Public_Safety_Fire_or_police_station            8
Public_Safety_Penitentiary                      8
Lodging_Other                                   8
Public_Assembly_Uncategorized                   8
Public_Assembly_Other                           7
Public_Safety_Courthouse                        5
Mixed_Use_Predominantly_Residential             5
Health_Care_Outpatient_Clinic                   5
Lodging_Uncategorized                           5
Office_Mixed_use                                4
Data_Center                                     4
Health_Care_Outpatient_Uncategorized            4
Food_Service_Uncategorized                      4
Public_Assembly_Stadium                         3
Food_Service_Other                              3
Education_Preschool_or_daycare                  3
Service_Drycleaning_or_Laundry                  2
Health_Care_Uncategorized                       2
Name: facility_type, dtype: int64
60000.0     27
50000.0     26
80000.0     25
100000.0    22
72000.0     20
            ..
232582.0     1
64600.0      1
280146.0     1
119688.0     1
45640.0      1
Name: floor_area, Length: 8536, dtype: int64
2000.0    176
1970.0    157
1925.0    154
1968.0    154
2008.0    152
         ...
1844.0      1
1873.0      1
1879.0      1
1869.0      1
1840.0      1
Name: year_built, Length: 164, dtype: int64
100.0    252
92.0     173
99.0     160
88.0     151
91.0     148
        ...
20.0      29
12.0      28
4.0       28
7.0       25
13.0      24
Name: energy_star_rating, Length: 100, dtype: int64
812.0    1428
15.2      905
26.5      705
241.4     493
130.8     475
33.5      421
231.3     396
182.9     354
18.3      301
56.1      287
43.9      278
18.6      225
260.0     202
229.8     196
6.1       192
186.5     187
118.9     186
135.0     183
3.0       180
44.2      179
45.7      165
201.8     154
30.5      144
197.5     136
57.3      131
2.4       128
266.1     115
59.1      114
35.4      107
58.5      100
189.3      94
134.1      86
189.0      72
126.5      65
216.4      65
178.0      53
21.3       52
152.4      41
109.7      30
214.0      29
182.3      22
32.0       15
1.8        10
163.1       4
Name: ELEVATION, dtype: int64
 21    3236
-1     2568
 15    1515
 2     1238
 38    1027
 12      85
 17      32
 10       4
Name: january_min_temp, dtype: int64
38.661290    3236
27.548387    2568
41.177419    1515
33.435484    1238
50.596774    1027
38.451613      85
29.741935      32
37.161290       4
Name: january_avg_temp, dtype: int64
54    3236
59    2568
71    1515
61    1238
64    1027
67      85
42      32
69       4
Name: january_max_temp, dtype: int64
28    3236
9     2568
22    1600
16    1238
40    1027
24      32
18       4
Name: february_min_temp, dtype: int64
41.625000    3236
36.053571    2568
45.685185    1515
37.660714    1238
54.482143    1027
44.178571      85
33.428571      32
41.857143       4
Name: february_avg_temp, dtype: int64
59    3236
69    2568
76    1515
73    1238
66    1027
74      89
52      32
Name: february_max_temp, dtype: int64
33    3236
12    2568
21    1515
8     1238
42    1027
15      85
26      32
18       4
Name: march_min_temp, dtype: int64
46.500000    3236
37.354839    2568
45.216667    1515
35.935484    1238
56.935484    1027
42.080645      85
38.338710      32
41.693548       4
Name: march_avg_temp, dtype: int64
80    4083
59    3236
69    1238
77    1116
53      32
Name: march_max_temp, dtype: int64
37    3321
29    2568
38    1515
28    1238
45    1027
31      32
32       4
Name: april_min_temp, dtype: int64
50.833333    3236
51.857143    2568
61.983333    1515
54.800000    1238
58.450000    1027
59.450000      85
42.766667      32
58.050000       4
Name: april_avg_temp, dtype: int64
67    3236
81    2568
93    1515
85    1238
78    1027
88      85
61      32
87       4
Name: april_max_temp, dtype: int64
42    3236
30    2568
40    1515
38    1238
49    1027
43      85
33      32
37       4
Name: may_min_temp, dtype: int64
58.112903    3236
56.596774    2568
64.629032    1515
59.096774    1238
60.903226    1027
63.096774      85
51.000000      32
60.435484       4
Name: may_avg_temp, dtype: int64
82    3236
88    2568
94    1515
92    1238
87    1027
93      85
80      32
91       4
Name: may_max_temp, dtype: int64
45    5804
51    2542
40    1238
53      85
41      32
48       4
Name: june_min_temp, dtype: int64
62.583333    3236
70.033333    2568
75.916667    1515
68.689655    1238
63.150000    1027
74.633333      85
55.583333      32
70.600000       4
Name: june_avg_temp, dtype: int64
93    3268
94    2568
96    1600
91    1238
97    1027
92       4
Name: june_max_temp, dtype: int64
51    3236
52    2568
53    2265
59    1515
62      85
46      32
55       4
Name: july_min_temp, dtype: int64
67.016129    3236
72.483871    2568
81.083333    1515
74.677419    1238
64.258065    1027
79.274194      85
60.467742      32
75.516129       4
Name: july_avg_temp, dtype: int64
84    3236
92    2568
98    1515
91    1242
85    1027
96      85
79      32
Name: july_max_temp, dtype: int64
53    4263
46    2600
60    1600
52    1238
55       4
Name: august_min_temp, dtype: int64
69.741935    3236
69.274194    2568
76.838710    1515
70.564516    1238
65.854839    1027
75.274194      85
63.946429      32
71.290323       4
Name: august_avg_temp, dtype: int64
89    3842
92    3321
93    1515
88    1027
Name: august_max_temp, dtype: int64
40    3806
48    3236
51    1515
54    1027
53      85
42      32
47       4
Name: september_min_temp, dtype: int64
64.866667    3236
66.333333    2568
71.016667    1515
66.250000    1238
69.766667    1027
71.433333      85
58.700000      32
66.450000       4
Name: september_avg_temp, dtype: int64
90     3268
91     2753
95     2568
104    1027
92       85
88        4
Name: september_max_temp, dtype: int64
36    3236
32    2600
38    1515
33    1238
48    1027
42      85
35       4
Name: october_min_temp, dtype: int64
53.177419    3236
56.112903    2568
63.160714    1515
58.129032    1238
64.193548    1027
64.080645      85
46.096774      32
59.266667       4
Name: october_avg_temp, dtype: int64
83    3810
72    3236
85    1515
91    1027
84      85
65      32
Name: october_max_temp, dtype: int64
30    3236
16    2568
25    1515
17    1238
43    1027
23      85
29      32
20       4
Name: november_min_temp, dtype: int64
46.616667    3236
36.850000    2568
47.833333    1515
41.583333    1238
58.050000    1027
47.483333      85
39.300000      32
44.700000       4
Name: november_avg_temp, dtype: int64
63    3236
62    2568
78    1515
74    1238
69    1027
75      85
54      32
76       4
Name: november_max_temp, dtype: int64
 28    3236
-8     2568
 15    1515
 3     1238
 38    1027
 9       85
 24      32
 11       4
Name: december_min_temp, dtype: int64
40.532258    3236
25.919355    2568
38.048387    1515
29.933333    1238
51.887097    1027
36.064516      85
34.403226      32
34.467742       4
Name: december_avg_temp, dtype: int64
64    4083
55    3236
57    1238
66    1027
63      85
47      32
61       4
Name: december_max_temp, dtype: int64
345     3236
761     2568
1643    1515
866     1238
342     1027
1490      85
110       32
988        4
Name: cooling_degree_days, dtype: int64
4478    3236
5907    2568
3555    1515
5264    1238
2112    1027
3949      85
6877      32
4473       4
Name: heating_degree_days, dtype: int64
44.83     3236
42.55     2568
41.06     1515
43.54     1238
25.24     1027
41.34       85
112.92      32
26.30        4
Name: precipitation_inches, dtype: int64
4.0     3236
10.2    2568
3.4     1515
27.3    1238
0.0     1027
23.3      85
84.5      32
8.3        4
Name: snowfall_inches, dtype: int64
10     3236
17     2568
6      1515
51     1238
0      1027
28       85
530      32
19        4
Name: snowdepth_inches, dtype: int64
53.420548    3236
50.584022    2568
59.428969    1515
52.646006    1238
59.894521    1027
58.013699      85
46.073204      32
55.168956       4
Name: avg_temp, dtype: int64
17     3236
108    2568
45     1515
97     1238
0      1027
46       85
55       32
67        4
Name: days_below_30F, dtype: int64
0     4263
51    2568
7     1515
45    1238
9      117
18       4
Name: days_below_20F, dtype: int64
0     5814
14    2568
13    1238
1       85
Name: days_below_10F, dtype: int64
0    7137
5    2568
Name: days_below_0F, dtype: int64
39     3236
79     2568
122    1515
77     1238
29     1027
102      85
15       32
81        4
Name: days_above_80F, dtype: int64
3     3236
12    2568
5     2265
41    1515
22      85
1       32
6        4
Name: days_above_90F, dtype: int64
0    8678
2    1027
Name: days_above_100F, dtype: int64
0    9705
Name: days_above_110F, dtype: int64
340.0    393
310.0    257
330.0    176
320.0    169
280.0    131
360.0      4
Name: direction_max_wind_speed, dtype: int64
320.0    341
340.0    265
240.0    192
350.0    176
270.0    131
330.0     25
Name: direction_peak_wind_speed, dtype: int64
20.6    196
14.8    192
19.2    187
17.9    176
18.3    154
16.5    131
20.1     65
17.4     15
22.8     10
23.3      4
Name: max_wind_speed, dtype: int64
129.0    176
138.0    154
250.0    131
123.0     72
34.0      41
126.0     10
107.0      4
Name: days_with_fog, dtype: int64
75757    1
82221    1
82223    1
82224    1
82225    1
        ..
78993    1
78994    1
78995    1
78996    1
85461    1
Name: id, Length: 9705, dtype: int64

In [22]:
def missing_values_table(df):
        # Total missing values by column
        mis_val = df.isnull().sum()
        
        # Percentage of missing values by column
        mis_val_percent = 100 * df.isnull().sum() / len(df)
        
        # build a table with the thw columns
        mis_val_table = pd.concat([mis_val, mis_val_percent], axis=1)
        
        # Rename the columns
        mis_val_table_ren_columns = mis_val_table.rename(
        columns = {0 : 'Missing Values', 1 : '% of Total Values'})
        
        # Sort the table by percentage of missing descending
        mis_val_table_ren_columns = mis_val_table_ren_columns[
            mis_val_table_ren_columns.iloc[:,1] != 0].sort_values(
        '% of Total Values', ascending=False).round(1)
        
        # Print some summary information
        print ("Your selected dataframe has " + str(df.shape[1]) + " columns.\n"      
            "There are " + str(mis_val_table_ren_columns.shape[0]) +
              " columns that have missing values.")
        
        # Return the dataframe with missing information
        return mis_val_table_ren_columns

In [23]:
print("Train set columns with null values: ")
missing_values_train = missing_values_table(train)
missing_values_train

Train set columns with null values:
Your selected dataframe has 64 columns.
There are 6 columns that have missing values.

                           Missing Values  % of Total Values
days_with_fog                       45796               60.5
direction_peak_wind_speed           41811               55.2
direction_max_wind_speed            41082               54.2
max_wind_speed                      41082               54.2
energy_star_rating                  26709               35.3
year_built                           1837                2.4

In [24]:
print("Test set columns with null values: ")
missing_values_test = missing_values_table(test)
missing_values_test

Test set columns with null values:
Your selected dataframe has 63 columns.
There are 6 columns that have missing values.

                           Missing Values  % of Total Values
days_with_fog                        9117               93.9
direction_max_wind_speed             8575               88.4
direction_peak_wind_speed            8575               88.4
max_wind_speed                       8575               88.4
energy_star_rating                   2254               23.2
year_built                             92                0.9

**Combining 2 Datasets**

In [25]:
test['site_eui']=y_test['site_eui']
comb = pd.concat([train, test],axis=0,ignore_index=True)

In [26]:
comb.head()

,id,Year_Factor,State_Factor,building_class,facility_type,floor_area,year_built,energy_star_rating,ELEVATION,january_min_temp,january_avg_temp,january_max_temp,february_min_temp,february_avg_temp,february_max_temp,march_min_temp,march_avg_temp,march_max_temp,april_min_temp,april_avg_temp,april_max_temp,may_min_temp,may_avg_temp,may_max_temp,june_min_temp,june_avg_temp,june_max_temp,july_min_temp,july_avg_temp,july_max_temp,august_min_temp,august_avg_temp,august_max_temp,september_min_temp,september_avg_temp,september_max_temp,october_min_temp,october_avg_temp,october_max_temp,november_min_temp,november_avg_temp,november_max_temp,december_min_temp,december_avg_temp,december_max_temp,cooling_degree_days,heating_degree_days,precipitation_inches,snowfall_inches,snowdepth_inches,avg_temp,days_below_30F,days_below_20F,days_below_10F,days_below_0F,days_above_80F,days_above_90F,days_above_100F,days_above_110F,direction_max_wind_speed,direction_peak_wind_speed,max_wind_speed,days_with_fog,site_eui
0,0,1,State_1,Commercial,Grocery_store_or_food_market,61242.0,1942.0,11.0,2.4,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,1.0,1.0,NaN,248.682615
1,1,1,State_1,Commercial,Warehouse_Distribution_or_Shipping_center,274000.0,1955.0,45.0,1.8,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,NaN,1.0,12.0,26.500150
2,2,1,State_1,Commercial,Retail_Enclosed_mall,280025.0,1951.0,97.0,1.8,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,NaN,1.0,12.0,24.693619
3,3,1,State_1,Commercial,Education_Other_classroom,55325.0,1980.0,46.0,1.8,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,NaN,1.0,12.0,48.406926
4,4,1,State_1,Commercial,Warehouse_Nonrefrigerated,66000.0,1985.0,100.0,2.4,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,1.0,1.0,NaN,3.899395

# Exploratory Data Analysis

In [27]:
comb.shape

(85462, 64)

In [28]:
comb.isna().sum().sort_values(ascending=False)

days_with_fog                54913
direction_peak_wind_speed    50386
max_wind_speed               49657
direction_max_wind_speed     49657
energy_star_rating           28963
                             ...
july_min_temp                    0
july_avg_temp                    0
july_max_temp                    0
august_min_temp                  0
site_eui                         0
Length: 64, dtype: int64

# Preprocessing

In [29]:
groupby_cols = ['State_Factor','building_class','facility_type','floor_area','year_built','Year_Factor']
comb = comb.sort_values(by=groupby_cols).reset_index(drop=True)

In [30]:
comb.loc[:,comb.dtypes=='object'].columns

Index(['State_Factor', 'building_class', 'facility_type'], dtype='object')

**KNN Imputing**

In [52]:
cats = ['State_Factor', 'facility_type', 'building_class']
le=LabelEncoder()
for col in cats:
    comb[col]=le.fit_transform(comb[col])

In [31]:
knn_imputing = True
target='site_eui'

if knn_imputing:
    imputer = KNNImputer(n_neighbors=7)
    tmp = comb[['State_Factor', 'building_class', 'facility_type', target]]
    df = comb.drop(tmp.columns, axis=1)
    df1 = pd.DataFrame(imputer.fit_transform(df),columns = df.columns)
    
    tmp.to_csv('imputer_tmp.csv', index=False)
    df1.to_csv('imputer_df1.csv', index=False)
    joblib.dump(imputer, 'knn_imputer.pkl')

else:
    df1 = pd.read_csv('imputer_df1.csv')
    tmp = comb[['State_Factor', 'building_class', 'facility_type', target]]
    comb = comb.drop(tmp.columns, axis=1)
    
    for col in tmp.columns:
        comb[col]=tmp[col]
    for col in df1.columns:
        comb[col] = df1[col]

**Target Encoder**

In [24]:
cats = ['State_Factor', 'building_class', 'facility_type']
for col in cats:
    encoder = TargetEncoder()
    comb[f'te_{col}'] = encoder.fit_transform(comb[col], comb[target])

# Feature Engineering

### Weather Stats

In [33]:
# extract new weather statistics from the building location weather features
temp = [col for col in comb.columns if 'temp' in col]

comb['min_temp'] = comb[temp].min(axis=1)
comb['max_temp'] = comb[temp].max(axis=1)
comb['avg_temp'] = comb[temp].mean(axis=1)
comb['std_temp'] = comb[temp].std(axis=1)
comb['skew_temp'] = comb[temp].skew(axis=1)


# by seasons
temp = pd.Series([col for col in comb.columns if 'temp' in col])

winter_temp = temp[temp.apply(lambda x: ('january' in x or 'february' in x or 'december' in x))].values
spring_temp = temp[temp.apply(lambda x: ('march' in x or 'april' in x or 'may' in x))].values
summer_temp = temp[temp.apply(lambda x: ('june' in x or 'july' in x or 'august' in x))].values
autumn_temp = temp[temp.apply(lambda x: ('september' in x or 'october' in x or 'november' in x))].values


### winter
comb['min_winter_temp'] = comb[winter_temp].min(axis=1)
comb['max_winter_temp'] = comb[winter_temp].max(axis=1)
comb['avg_winter_temp'] = comb[winter_temp].mean(axis=1)
comb['std_winter_temp'] = comb[winter_temp].std(axis=1)
comb['skew_winter_temp'] = comb[winter_temp].skew(axis=1)
### spring
comb['min_spring_temp'] = comb[spring_temp].min(axis=1)
comb['max_spring_temp'] = comb[spring_temp].max(axis=1)
comb['avg_spring_temp'] = comb[spring_temp].mean(axis=1)
comb['std_spring_temp'] = comb[spring_temp].std(axis=1)
comb['skew_spring_temp'] = comb[spring_temp].skew(axis=1)
### summer
comb['min_summer_temp'] = comb[summer_temp].min(axis=1)
comb['max_summer_temp'] = comb[summer_temp].max(axis=1)
comb['avg_summer_temp'] = comb[summer_temp].mean(axis=1)
comb['std_summer_temp'] = comb[summer_temp].max(axis=1)
comb['skew_summer_temp'] = comb[summer_temp].skew(axis=1)
## autumn
comb['min_autumn_temp'] = comb[autumn_temp].min(axis=1)
comb['max_autumn_temp'] = comb[autumn_temp].max(axis=1)
comb['avg_autumn_temp'] = comb[autumn_temp].mean(axis=1)
comb['std_autumn_temp'] = comb[autumn_temp].std(axis=1)
comb['skew_autumn_temp'] = comb[autumn_temp].skew(axis=1)

In [34]:
comb['month_cooling_degree_days'] = comb['cooling_degree_days']/12
comb['month_heating_degree_days'] = comb['heating_degree_days']/12

### Building Stats

In [35]:
# total area
comb['building_area'] = comb['floor_area'] * comb['ELEVATION']
# rating energy by floor
comb['floor_energy_star_rating'] = comb['energy_star_rating']/comb['ELEVATION']

In [29]:
nums = train.loc[:, train.dtypes != 'object'].columns
comb[nums].skew().sort_values(key=abs, ascending=False)[:5]

days_above_110F    89.873857
days_above_100F    24.615438
year_built        -11.716545
floor_area          6.701786
ELEVATION           5.140444
dtype: float64

In [30]:
skewed = ['days_above_110F', 'days_above_100F']

for var in skewed:
    
    # map the variable values into 0 and 1
    comb[var] = np.where(comb[var]==0, 0, 1)

In [5]:
saved = True
if saved:
    data_path = 'feature_transformed_set.pkl'
    with open(data_path, "rb") as fh:
        comb = pickle.load(fh)
else:
    comb.to_pickle('feature_transformed_set.pkl')

In [6]:
comb.shape

(85462, 164)

In [7]:
comb.head()

,id,Year_Factor,floor_area,year_built,energy_star_rating,ELEVATION,january_min_temp,january_avg_temp,january_max_temp,february_min_temp,february_avg_temp,february_max_temp,march_min_temp,march_avg_temp,march_max_temp,april_min_temp,april_avg_temp,april_max_temp,may_min_temp,may_avg_temp,may_max_temp,june_min_temp,june_avg_temp,june_max_temp,july_min_temp,july_avg_temp,july_max_temp,august_min_temp,august_avg_temp,august_max_temp,september_min_temp,september_avg_temp,september_max_temp,october_min_temp,october_avg_temp,...,State_Factor,building_class,facility_type,site_eui,te_State_Factor,te_building_class,te_facility_type,min_temp,max_temp,std_temp,skew_temp,min_winter_temp,max_winter_temp,avg_winter_temp,std_winter_temp,skew_winter_temp,min_spring_temp,max_spring_temp,avg_spring_temp,std_spring_temp,skew_spring_temp,min_summer_temp,max_summer_temp,avg_summer_temp,std_summer_temp,skew_summer_temp,min_autumn_temp,max_autumn_temp,avg_autumn_temp,std_autumn_temp,skew_autumn_temp,month_cooling_degree_days,month_heating_degree_days,building_area,floor_energy_star_rating
0,1456.0,3.0,10149.0,1931.0,38.428571,45.7,26.0,44.516129,64.0,30.0,49.392857,69.0,37.0,55.967742,77.0,40.0,61.783333,90.0,45.0,65.129032,91.0,52.0,70.016667,104.0,52.0,71.387097,102.0,54.0,71.322581,97.0,47.0,69.133333,98.0,43.0,61.000000,...,State_1,Commercial,Commercial_Other,6.800000,62.02231,85.176286,94.083583,24.0,104.0,21.308416,0.281828,24.0,69.0,46.699565,17.630529,0.021018,37.0,91.0,62.542234,20.284168,0.250054,52.0,104.0,74.858483,104.0,0.377041,36.0,98.0,63.361111,20.462133,0.360253,68.833333,211.833333,463809.3,0.840888
1,2673.0,4.0,10149.0,1931.0,43.571429,120.4,41.0,55.096774,73.0,42.0,54.875000,71.0,47.0,59.032258,76.0,47.0,60.100000,90.0,51.0,63.483871,92.0,52.0,64.250000,87.0,53.0,66.903226,90.0,57.0,67.016129,80.0,56.0,68.383333,83.0,55.0,68.661290,...,State_1,Commercial,Commercial_Other,8.200000,62.02231,85.176286,94.083583,41.0,95.0,14.980311,0.428700,41.0,73.0,55.862455,12.779553,0.081583,47.0,92.0,65.068459,17.251378,0.670141,52.0,90.0,68.574373,90.0,0.430796,46.0,95.0,67.521625,15.342943,0.494753,41.416667,123.083333,1221939.6,0.361889
2,3769.0,5.0,10149.0,1931.0,37.571429,59.1,29.0,51.387097,77.0,36.0,56.803571,75.0,40.0,61.435484,85.0,41.0,60.966667,91.0,45.0,62.887097,90.0,55.0,72.983333,106.0,60.0,74.516129,103.0,58.0,74.774194,104.0,53.0,73.583333,105.0,49.0,69.580645,...,State_1,Commercial,Commercial_Other,12.300000,62.02231,85.176286,94.083583,28.0,106.0,21.906277,0.212369,28.0,77.0,52.196813,18.727631,0.005259,40.0,91.0,64.143250,20.398627,0.230872,55.0,106.0,78.697073,106.0,0.404631,29.0,105.0,67.003405,23.881873,0.162329,109.916667,151.916667,599805.9,0.635726
3,76077.0,7.0,10149.0,1931.0,60.285714,59.1,38.0,50.596774,64.0,40.0,54.482143,66.0,42.0,56.935484,77.0,45.0,58.450000,78.0,49.0,60.903226,87.0,51.0,63.150000,97.0,53.0,64.258065,85.0,53.0,65.854839,88.0,54.0,69.766667,104.0,48.0,64.193548,...,State_1,Commercial,Commercial_Other,15.036394,62.02231,85.176286,94.083583,38.0,104.0,16.708230,0.725826,38.0,66.0,52.107335,11.619161,-0.034349,42.0,87.0,61.587634,15.818993,0.417654,51.0,97.0,68.918100,97.0,0.628608,43.0,104.0,66.778913,19.843743,0.883927,28.500000,176.000000,599805.9,1.020063
4,2144.0,3.0,10755.0,1937.0,45.571429,9.1,22.0,44.790323,65.0,25.0,47.892857,71.0,32.0,53.112903,79.0,34.0,58.866667,87.0,35.0,62.096774,91.0,44.0,66.283333,99.0,48.0,65.693548,91.0,45.0,67.080645,92.0,42.0,65.950000,96.0,35.0,56.967742,...,State_1,Commercial,Commercial_Other,63.083288,62.02231,85.176286,94.083583,16.0,99.0,22.272150,0.113857,16.0,71.0,44.780210,20.572244,-0.084189,32.0,91.0,59.119594,22.864101,0.160184,44.0,99.0,68.673059,99.0,0.247420,31.0,96.0,60.048268,22.548770,0.276234,25.250000,259.000000,97870.5,5.007849

In [56]:
cols=['floor_area','energy_star_rating','ELEVATION','january_avg_temp','february_avg_temp','march_avg_temp',
     'april_avg_temp','may_avg_temp','june_avg_temp','july_avg_temp','august_avg_temp','september_avg_temp',
     'october_avg_temp','november_avg_temp','december_avg_temp','State_Factor','building_class','facility_type','building_area',
     'avg_winter_temp','avg_spring_temp','avg_summer_temp','avg_autumn_temp','site_eui']

In [57]:
x['State_Factor'].value_counts()

5    50840
2     9680
4     6868
0     6645
3     6386
6     5024
1       19
Name: State_Factor, dtype: int64

### Train Test Split

In [60]:
x=pd.DataFrame()
for i in cols:
    x[i]=comb[i]
y=x['site_eui']
x.drop('site_eui',axis=1,inplace=True)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,train_size=0.75,random_state=42)

# Model Building

### XGBRegressor

In [61]:
xgb = XGBRegressor(n_estimators=500, reg_alpha=0.01)
xgb.fit(x_train, y_train)
y_pred = xgb.predict(x_test)
print(" RMSE:", np.sqrt(mean_squared_error(y_test,y_pred)))

 RMSE: 37.681080113302365

In [62]:
joblib.dump(xgb,'site_eui.sav')

['site_eui.sav']

### Random Forest Regressor

In [57]:
rf = RandomForestRegressor(random_state=42, criterion='mse', max_depth = 15, min_samples_split= 2)
rf.fit(x_train, y_train)
y_pred = rf.predict(x_test)
print(" RMSE:", np.sqrt(mean_squared_error(y_test,y_pred)))

 RMSE: 39.04534959292543

In [58]:
joblib.dump(xgb,'site_eui_xgb.sav')

['site_eui_xgb.sav']

In [2]:
xgb=joblib.load('site_eui_xgb.sav')

# Hyperparameter Tuning

In [16]:
def objective(trial):
    params={
        'n_estimators': trial.suggest_int('n_estimators',500,600),
        'eta': trial.suggest_float('eta',0.1,0.4),
        'reg_alpha': trial.suggest_float('reg_alpha',0.1,1)
        #'reg_lambda': trial.suggest_float('reg_lambda',0.1,1)
    }
    model=XGBRegressor(**params)
    model.fit(x_train,y_train)
    y_pred = model.predict(x_test)
    #pred_labels = np.rint(preds)
    accuracy = np.sqrt(mean_squared_error(y_test,y_pred))
    return accuracy

In [19]:
study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=50, timeout=6000)

[I 2022-07-25 23:38:20,006] A new study created in memory with name: no-name-17c50f1c-8a90-4282-9a9d-9cf78f4e3552
[I 2022-07-25 23:39:30,615] Trial 0 finished with value: 36.81420429493147 and parameters: {'n_estimators': 548, 'eta': 0.1596136223174804, 'reg_alpha': 0.3766244237711439}. Best is trial 0 with value: 36.81420429493147.
[I 2022-07-25 23:40:36,733] Trial 1 finished with value: 37.36907814322374 and parameters: {'n_estimators': 504, 'eta': 0.2874081408516843, 'reg_alpha': 0.9295453016777103}. Best is trial 0 with value: 36.81420429493147.
[I 2022-07-25 23:41:51,531] Trial 2 finished with value: 37.202712998875754 and parameters: {'n_estimators': 570, 'eta': 0.3864508742668811, 'reg_alpha': 0.1728583505188911}. Best is trial 0 with value: 36.81420429493147.
[I 2022-07-25 23:43:10,410] Trial 3 finished with value: 37.03125365206325 and parameters: {'n_estimators': 598, 'eta': 0.127395186118603, 'reg_alpha': 0.6533544374975014}. Best is trial 0 with value: 36.81420429493147.
[I 2022-07-25 23:44:29,722] Trial 4 finished with value: 36.5206805560659 and parameters: {'n_estimators': 590, 'eta': 0.20555270689879293, 'reg_alpha': 0.38711810433108007}. Best is trial 4 with value: 36.5206805560659.
[I 2022-07-25 23:45:41,954] Trial 5 finished with value: 37.1322896370636 and parameters: {'n_estimators': 546, 'eta': 0.27994090304865593, 'reg_alpha': 0.13408551256255039}. Best is trial 4 with value: 36.5206805560659.
[I 2022-07-25 23:46:53,612] Trial 6 finished with value: 36.671293987505614 and parameters: {'n_estimators': 545, 'eta': 0.2146968316922757, 'reg_alpha': 0.36896010440706173}. Best is trial 4 with value: 36.5206805560659.
[I 2022-07-25 23:48:14,109] Trial 7 finished with value: 37.60378352407833 and parameters: {'n_estimators': 600, 'eta': 0.3962882286102831, 'reg_alpha': 0.7275121099737311}. Best is trial 4 with value: 36.5206805560659.
[I 2022-07-25 23:49:30,394] Trial 8 finished with value: 37.0730092801578 and parameters: {'n_estimators': 560, 'eta': 0.3069889342198787, 'reg_alpha': 0.13992289849972017}. Best is trial 4 with value: 36.5206805560659.
[I 2022-07-25 23:50:43,728] Trial 9 finished with value: 36.652445215704454 and parameters: {'n_estimators': 556, 'eta': 0.2954876159051514, 'reg_alpha': 0.17805816900231033}. Best is trial 4 with value: 36.5206805560659.
[I 2022-07-25 23:51:59,756] Trial 10 finished with value: 36.83856605672802 and parameters: {'n_estimators': 582, 'eta': 0.19390837751719292, 'reg_alpha': 0.4704685834314929}. Best is trial 4 with value: 36.5206805560659.
[I 2022-07-25 23:53:09,095] Trial 11 finished with value: 36.940769498220135 and parameters: {'n_estimators': 521, 'eta': 0.23248717690509035, 'reg_alpha': 0.35838372299655835}. Best is trial 4 with value: 36.5206805560659.
[I 2022-07-25 23:54:26,730] Trial 12 finished with value: 37.452265691674356 and parameters: {'n_estimators': 581, 'eta': 0.35068886568313795, 'reg_alpha': 0.2556028051719587}. Best is trial 4 with value: 36.5206805560659.
[I 2022-07-25 23:55:35,581] Trial 13 finished with value: 37.18785398825369 and parameters: {'n_estimators': 525, 'eta': 0.10173741160152265, 'reg_alpha': 0.5611051763364822}. Best is trial 4 with value: 36.5206805560659.
[I 2022-07-25 23:56:51,775] Trial 14 finished with value: 36.869765310253186 and parameters: {'n_estimators': 581, 'eta': 0.24726235614480374, 'reg_alpha': 0.30008941533287203}. Best is trial 4 with value: 36.5206805560659.
[I 2022-07-25 23:58:07,118] Trial 15 finished with value: 37.145536576636154 and parameters: {'n_estimators': 563, 'eta': 0.32883059555478145, 'reg_alpha': 0.5158246602972756}. Best is trial 4 with value: 36.5206805560659.
[I 2022-07-25 23:59:17,989] Trial 16 finished with value: 36.92421189791518 and parameters: {'n_estimators': 532, 'eta': 0.18018950259372096, 'reg_alpha': 0.24385544579878304}. Best is trial 4 with value: 36.5206805560659.
[I 2022-07-26 00:00:36,177] Trial 17 finished with value: 36.82835022748151 and parameters: {'n_estimators': 590, 'eta': 0.2638433661241419, 'reg_alpha': 0.44516324469954555}. Best is trial 4 with value: 36.5206805560659.

KeyboardInterrupt:

In [20]:
print("Number of finished trials: {}".format(len(study.trials)))

print("Best trial:")
trial = study.best_trial

print("  Value: {}".format(trial.value))

print("  Params: ")
for key, value in trial.params.items():
    print("    {}: {}".format(key, value))

Number of finished trials: 19
Best trial:
  Value: 36.5206805560659
  Params:
    n_estimators: 590
    eta: 0.20555270689879293
    reg_alpha: 0.38711810433108007